---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    team: devops-by-example
  name: {{ include "sample-app.fullname" . }}
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: http
  namespaceSelector:
    matchNames:
    - staging
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app