---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
    team: devops-by-example
  name: {{ include "sample-app.fullname" . }}
  namespace: staging
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 4 }}